version: "3"
networks:
  net:
    driver: bridge
services:
  traefik:
    image: traefik:2.10.7
    container_name: traefik
    network_mode: "host"
    volumes:
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    command:
      - '--api'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--providers.file.filename=/etc/traefik/certificates.yml'
      - '--entrypoints.http=true'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.http.http.redirections.entrypoint.to=https'
      - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.https=true'
      - '--entrypoints.https.address=:443'
      - '--certificatesresolvers.myresolver.acme.email=<change-me>'
      - '--certificatesresolvers.myresolver.acme.storage=acme.json'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http'
      - '--log=true'
      - '--log.level=DEBUG'
      - '--log.filepath=/var/log/traefik.log'

  vault:
    image: hashicorp/vault
    hostname: vault
    container_name: vault
    ports:
      - 8200:8200
    volumes:
      - "./:/vault/config/config.hcl"
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl
    restart: unless-stopped
    labels:
      - 'traefik.http.routers.vault.rule=Host(`vault.<change-me>`)'
      - 'traefik.enable=true'
      - 'traefik.http.routers.vault.entrypoints=https'
      - 'traefik.http.routers.vault.tls=true'
      - 'traefik.http.routers.vault.tls.options=default'
      - 'traefik.http.routers.vault.tls.certresolver=myresolver'
volumes:
  etc_traefik:
  vault:

networks:
  host:
    external: true