kind: Namespace
apiVersion: v1
metadata:
  name: hcloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hcloud-csi-driver
  namespace: kube-system
  # annotations:
  #   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: hcloud-secret
    creationPolicy: Owner
  data:
  - secretKey: hcloudApiToken
    remoteRef:
      key: hetzner
      property: hcloudApiToken
  - secretKey: token
    remoteRef:
      key: hetzner
      property: token
  dataFrom:
    - extract:
        key: hetzner
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi-driver
  namespace: argocd
spec:
  destination:
    namespace: kubesystem
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: hcloud-csi-driver
    repoURL: https://helm-charts.mlohr.com/
    targetRevision: 2.2.1
    helm: 
      values: |
        secret:
          existingSecretName: hcloud-secret
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true