kind: Namespace
apiVersion: v1
metadata:
  name: metallb-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.12
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  # This is a workaround for mutated CRD, where ingoreDifferences must be set
  # https://github.com/metallb/metallb/issues/1681
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  info:
    - name: workaround1
      value: "https://github.com/metallb/metallb/issues/1681"
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-address-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    - 128.140.15.44/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ipAddressPools:
  - main-address-pool
  interfaces:
  - eth0
  # nodeSelectors:
  # - matchLabels:
  #     kubernetes.io/hostname: argo