---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./authentik-charts.yaml
- ./bitnami-charts.yaml
- ./bjw-s-charts.yaml
- ./dysnix-charts.yaml
- ./external-dns-charts.yaml
- ./grafana-charts.yaml
- ./ingress-nginx-charts.yaml
- ./jetstack-charts.yaml
- ./k8s-at-home-charts.yaml
- ./kyverno-charts.yaml
- ./metallb-charts.yaml
- ./metrics-server-charts.yaml
- ./mlohr-charts.yaml
- ./node-feature-discovery-charts.yaml
- ./prometheus-community-charts.yaml
